### ISSUE TITLE
Use system environment variable instead of config.ini

### ISSUE THREAD

**Issue by emersonmello** [NikolaiMagnussen/Git-Gud-tool#3]
Hi @NikolaiMagnussen ,

Currently, to clone github classroom repositories I have to stay inside of git-gud-tool directory, because `git_gud.py` script has to import `config.py` and to read `config.ini`. It leaves current directory a little mess. 

I moved from these config files to system environment variable (to get GITHUB TOKEN) and I left `git_gud.py` script in a specific directory that is on my `PATH`. So, now I'm able to use `git_gud.py` everywhere.

Please, have a look at my propose bellow to use  system environment variable inside of `git_gud.py`.

```python
import os
import sys
import subprocess
from github import Github, GithubException
import configparser

# Try to get it from system environment variable 
# (On Linux/macOS you have to create it on $HOME/.bash_profile)
key = os.environ.get('GIT_GUD_TOKEN', None)

GIT_GUD_CONFIG = {
    'owners': {
        "GitHub_User_Name1",
        "GitHub_User_Name2",
        "GitHub_User_Name3"
    },

    'grading_file': "GRADING.md",

    'passed': 'Result: PASS',

    'failed': 'Result: FAIL',

    'commit_msg': 'Graded project, see the {}-file in the root directory',

}

def print_help():
# your current code....

```

I mean, we don't need to keep `GIT_GUD_CONFIG` on a different file and we still leave GITHUB API KEY out of `git_gud.py` file.

Please, let me know your thoughts

**Comment by NikolaiMagnussen** [comment]
I think both having it persistent in a specific file, as well as in an environment variable would be the preferred.

To support this, it would probably be a good idea to set the API key.
